// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/compiladorv2/Lexer.flex

package compiladorv2;

@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\12\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\0\22\27\1\30\7\27\1\0\1\31"+
    "\2\0\1\27\1\0\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\27\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\27\1\51\1\52\1\53\1\54"+
    "\1\27\1\55\3\27\1\56\1\57\1\60\7\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\13\23\1\24\1\25"+
    "\1\26\1\27\1\0\1\30\4\0\1\31\1\32\1\33"+
    "\1\34\6\23\1\35\10\23\1\36\10\23\1\37\10\23"+
    "\1\40\1\41\5\23\1\42\4\23\1\43\1\23\1\44"+
    "\1\45\2\23\1\46\1\47\1\50\3\23\1\51\1\52"+
    "\1\53\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\61\0\142\0\223\0\61\0\304"+
    "\0\61\0\61\0\61\0\365\0\61\0\365\0\61\0\u0126"+
    "\0\61\0\61\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c"+
    "\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\61\0\61\0\61\0\61\0\223\0\61\0\u0405\0\u0436"+
    "\0\u0467\0\u0498\0\u04c9\0\61\0\61\0\61\0\u04fa\0\u052b"+
    "\0\u055c\0\u058d\0\u05be\0\u05ef\0\u01ea\0\u0620\0\u0651\0\u0682"+
    "\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\61\0\u07a8\0\u07d9"+
    "\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u01ea\0\u0930"+
    "\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u01ea"+
    "\0\u01ea\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u01ea\0\u0bad"+
    "\0\u0bde\0\u0c0f\0\u0c40\0\u01ea\0\u0c71\0\u01ea\0\u01ea\0\u0ca2"+
    "\0\u0cd3\0\u01ea\0\u01ea\0\u01ea\0\u0d04\0\u0d35\0\u0d66\0\u01ea"+
    "\0\u01ea\0\u01ea\0\u01ea";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\2\1\26\1\30\1\31\1\32\1\26\1\33"+
    "\2\26\1\34\5\26\1\35\1\26\1\36\1\37\1\26"+
    "\1\40\1\41\1\42\1\43\106\0\1\44\33\0\6\45"+
    "\1\46\22\45\1\47\27\45\10\50\1\0\20\50\1\51"+
    "\27\50\21\0\1\52\56\0\1\53\1\0\1\20\64\0"+
    "\1\54\60\0\1\55\60\0\1\56\54\0\1\26\5\0"+
    "\2\26\1\0\24\26\24\0\1\26\5\0\2\26\1\0"+
    "\21\26\1\57\2\26\24\0\1\26\5\0\2\26\1\0"+
    "\15\26\1\60\1\26\1\61\4\26\24\0\1\26\5\0"+
    "\2\26\1\0\1\62\6\26\1\63\14\26\24\0\1\26"+
    "\5\0\2\26\1\0\4\26\1\64\10\26\1\65\6\26"+
    "\24\0\1\26\5\0\2\26\1\0\1\66\11\26\1\67"+
    "\11\26\24\0\1\26\5\0\2\26\1\0\14\26\1\70"+
    "\7\26\24\0\1\26\5\0\2\26\1\0\17\26\1\71"+
    "\4\26\24\0\1\26\5\0\2\26\1\0\23\26\1\72"+
    "\24\0\1\26\5\0\2\26\1\0\17\26\1\73\4\26"+
    "\24\0\1\26\5\0\2\26\1\0\7\26\1\74\7\26"+
    "\1\75\4\26\3\0\2\45\3\0\54\45\10\0\1\76"+
    "\50\0\2\50\3\0\54\50\17\0\1\53\1\0\1\52"+
    "\60\0\1\53\60\0\1\26\5\0\2\26\1\0\17\26"+
    "\1\77\4\26\24\0\1\26\5\0\2\26\1\0\15\26"+
    "\1\100\6\26\24\0\1\26\5\0\2\26\1\0\4\26"+
    "\1\101\17\26\24\0\1\26\5\0\2\26\1\0\20\26"+
    "\1\102\3\26\24\0\1\26\5\0\2\26\1\0\1\103"+
    "\23\26\24\0\1\26\5\0\2\26\1\0\5\26\1\104"+
    "\16\26\24\0\1\26\5\0\2\26\1\0\12\26\1\105"+
    "\11\26\24\0\1\26\5\0\2\26\1\0\15\26\1\106"+
    "\6\26\24\0\1\26\5\0\2\26\1\0\21\26\1\107"+
    "\2\26\24\0\1\26\5\0\2\26\1\0\15\26\1\110"+
    "\6\26\24\0\1\26\5\0\2\26\1\0\10\26\1\111"+
    "\13\26\24\0\1\26\5\0\2\26\1\0\22\26\1\112"+
    "\1\26\24\0\1\26\5\0\2\26\1\0\10\26\1\113"+
    "\13\26\24\0\1\26\5\0\2\26\1\0\10\26\1\114"+
    "\13\26\24\0\1\26\5\0\2\26\1\0\10\26\1\115"+
    "\13\26\24\0\1\26\5\0\2\26\1\0\12\26\1\116"+
    "\11\26\24\0\1\26\5\0\2\26\1\0\1\117\23\26"+
    "\24\0\1\26\5\0\2\26\1\0\4\26\1\120\17\26"+
    "\24\0\1\26\5\0\2\26\1\0\17\26\1\121\4\26"+
    "\24\0\1\26\5\0\2\26\1\0\1\122\23\26\24\0"+
    "\1\26\5\0\2\26\1\0\20\26\1\123\3\26\24\0"+
    "\1\26\5\0\2\26\1\0\1\124\23\26\24\0\1\26"+
    "\5\0\2\26\1\0\6\26\1\125\15\26\24\0\1\26"+
    "\5\0\2\26\1\0\21\26\1\126\2\26\24\0\1\26"+
    "\5\0\2\26\1\0\4\26\1\127\17\26\24\0\1\26"+
    "\5\0\2\26\1\0\12\26\1\130\11\26\24\0\1\26"+
    "\5\0\2\26\1\0\21\26\1\131\2\26\24\0\1\26"+
    "\5\0\2\26\1\0\14\26\1\132\7\26\24\0\1\26"+
    "\5\0\2\26\1\0\4\26\1\133\17\26\24\0\1\26"+
    "\5\0\2\26\1\0\11\26\1\134\12\26\24\0\1\26"+
    "\5\0\2\26\1\0\22\26\1\135\1\26\24\0\1\26"+
    "\5\0\2\26\1\0\4\26\1\136\17\26\24\0\1\26"+
    "\5\0\2\26\1\0\21\26\1\137\2\26\24\0\1\26"+
    "\5\0\2\26\1\0\17\26\1\140\4\26\24\0\1\26"+
    "\5\0\2\26\1\0\2\26\1\141\21\26\24\0\1\26"+
    "\5\0\2\26\1\0\4\26\1\142\17\26\24\0\1\26"+
    "\5\0\2\26\1\0\4\26\1\143\17\26\24\0\1\26"+
    "\5\0\2\26\1\0\6\26\1\144\15\26\24\0\1\26"+
    "\5\0\2\26\1\0\1\145\23\26\24\0\1\26\5\0"+
    "\2\26\1\0\12\26\1\146\11\26\24\0\1\26\5\0"+
    "\2\26\1\0\1\147\23\26\24\0\1\26\5\0\2\26"+
    "\1\0\7\26\1\150\14\26\24\0\1\26\5\0\2\26"+
    "\1\0\14\26\1\151\7\26\24\0\1\26\5\0\2\26"+
    "\1\0\21\26\1\152\2\26\24\0\1\26\5\0\2\26"+
    "\1\0\13\26\1\153\10\26\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3479];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\2\1\1\11\1\1\3\11\1\1\1\11"+
    "\1\1\1\11\1\1\2\11\16\1\4\11\1\0\1\11"+
    "\4\0\1\1\3\11\17\1\1\11\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public int linea = 1;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Error: Token desconocido '" + yytext() + "' en la línea " + linea);
            }
          // fall through
          case 45: break;
          case 2:
            { /* ignora espacios en blanco */
            }
          // fall through
          case 46: break;
          case 3:
            { linea++;
            }
          // fall through
          case 47: break;
          case 4:
            { return new Token(Tokens.not.ordinal(), yytext(), linea);
            }
          // fall through
          case 48: break;
          case 5:
            { return new Token(Tokens.and.ordinal(), yytext(), linea);
            }
          // fall through
          case 49: break;
          case 6:
            { return new Token(Tokens.p_a.ordinal(), yytext(), linea);
            }
          // fall through
          case 50: break;
          case 7:
            { return new Token(Tokens.p_c.ordinal(), yytext(), linea);
            }
          // fall through
          case 51: break;
          case 8:
            { return new Token(Tokens.mul.ordinal(), yytext(), linea);
            }
          // fall through
          case 52: break;
          case 9:
            { return new Token(Tokens.sum.ordinal(), yytext(), linea);
            }
          // fall through
          case 53: break;
          case 10:
            { return new Token(Tokens.coma.ordinal(), yytext(), linea);
            }
          // fall through
          case 54: break;
          case 11:
            { return new Token(Tokens.res.ordinal(), yytext(), linea);
            }
          // fall through
          case 55: break;
          case 12:
            { return new Token(Tokens.div.ordinal(), yytext(), linea);
            }
          // fall through
          case 56: break;
          case 13:
            { return new Token(Tokens.nume.ordinal(), yytext(), linea);
            }
          // fall through
          case 57: break;
          case 14:
            { return new Token(Tokens.puntos.ordinal(), yytext(), linea);
            }
          // fall through
          case 58: break;
          case 15:
            { return new Token(Tokens.pcoma.ordinal(), yytext(), linea);
            }
          // fall through
          case 59: break;
          case 16:
            { return new Token(Tokens.me.ordinal(), yytext(), linea);
            }
          // fall through
          case 60: break;
          case 17:
            { return new Token(Tokens.igual.ordinal(), yytext(), linea);
            }
          // fall through
          case 61: break;
          case 18:
            { return new Token(Tokens.ma.ordinal(), yytext(), linea);
            }
          // fall through
          case 62: break;
          case 19:
            { return new Token(Tokens.id.ordinal(), yytext(), linea);
            }
          // fall through
          case 63: break;
          case 20:
            { return new Token(Tokens.l_a.ordinal(), yytext(), linea);
            }
          // fall through
          case 64: break;
          case 21:
            { return new Token(Tokens.or.ordinal(), yytext(), linea);
            }
          // fall through
          case 65: break;
          case 22:
            { return new Token(Tokens.l_c.ordinal(), yytext(), linea);
            }
          // fall through
          case 66: break;
          case 23:
            { return new Token(Tokens.dif.ordinal(), yytext(), linea);
            }
          // fall through
          case 67: break;
          case 24:
            { return new Token(Tokens.lits.ordinal(), yytext(), linea);
            }
          // fall through
          case 68: break;
          case 25:
            { return new Token(Tokens.numf.ordinal(), yytext(), linea);
            }
          // fall through
          case 69: break;
          case 26:
            { return new Token(Tokens.mai.ordinal(), yytext(), linea);
            }
          // fall through
          case 70: break;
          case 27:
            { return new Token(Tokens.exa.ordinal(), yytext(), linea);
            }
          // fall through
          case 71: break;
          case 28:
            { return new Token(Tokens.mei.ordinal(), yytext(), linea);
            }
          // fall through
          case 72: break;
          case 29:
            { return new Token(Tokens.edo.ordinal(), yytext(), linea);
            }
          // fall through
          case 73: break;
          case 30:
            { return new Token(Tokens.litc.ordinal(), yytext(), linea);
            }
          // fall through
          case 74: break;
          case 31:
            { return new Token(Tokens.tint.ordinal(), yytext(), linea);
            }
          // fall through
          case 75: break;
          case 32:
            { return new Token(Tokens.eca.ordinal(), yytext(), linea);
            }
          // fall through
          case 76: break;
          case 33:
            { return new Token(Tokens.tchar.ordinal(), yytext(), linea);
            }
          // fall through
          case 77: break;
          case 34:
            { return new Token(Tokens.ver.ordinal(), yytext(), linea);
            }
          // fall through
          case 78: break;
          case 35:
            { return new Token(Tokens.ebr.ordinal(), yytext(), linea);
            }
          // fall through
          case 79: break;
          case 36:
            { return new Token(Tokens.fal.ordinal(), yytext(), linea);
            }
          // fall through
          case 80: break;
          case 37:
            { return new Token(Tokens.tfloat.ordinal(), yytext(), linea);
            }
          // fall through
          case 81: break;
          case 38:
            { return new Token(Tokens.ewh.ordinal(), yytext(), linea);
            }
          // fall through
          case 82: break;
          case 39:
            { return new Token(Tokens.write.ordinal(), yytext(), linea);
            }
          // fall through
          case 83: break;
          case 40:
            { return new Token(Tokens.tString.ordinal(), yytext(), linea);
            }
          // fall through
          case 84: break;
          case 41:
            { return new Token(Tokens.esw.ordinal(), yytext(), linea);
            }
          // fall through
          case 85: break;
          case 42:
            { return new Token(Tokens.tboolean.ordinal(), yytext(), linea);
            }
          // fall through
          case 86: break;
          case 43:
            { return new Token(Tokens.ede.ordinal(), yytext(), linea);
            }
          // fall through
          case 87: break;
          case 44:
            { return new Token(Tokens.pro.ordinal(), yytext(), linea);
            }
          // fall through
          case 88: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
